########################################################
# OpenUnvierse configuration properties file (Example) #
########################################################

# -----------------------------
# JAR SIGNING CONFIG
# -----------------------------

SIGN_JAR_KEYSTORE="$HOME/keystore.p12" # Use unexisting keystore file to generate default keystore (⚠️ WARNING! NOT RECOMMENDED IN PRODUCTION!)
SIGN_JAR_STORETYPE="PKCS12"
SIGN_JAR_ALIAS="signing_alias"
SIGN_JAR_KEYPASS="your_password"
SIGN_JAR_STOREPASS="your_password"
SIGN_JAR_TSA="http://timestamp.digicert.com"

# -----------------------------
# APP IMAGE SIGNING CONFIG
# -----------------------------

# Generate a secure GPG key pair using the following command:
# gpg --batch --passphrase 'YOUR_STRONG_PASSWORD' --pinentry-mode loopback --gen-key <(echo -e 'Key-Type: RSA\nKey-Length: 4096\nSubkey-Type: RSA\nSubkey-Length: 4096\nName-Real: YourName\nName-Email: your-mail@example.com\nExpire-Date: 0\n%commit')
#
# ⚠️ Replace `'YOUR_STRONG_PASSWORD'` with a secure passphrase.<br>
# ⚠️ Replace `YourName` with your name.<br>
# ⚠️ Replace `your-mail@example.com` with your email address.
#
# List Your Secret Keys
# gpg --list-secret-keys

#YOUR_40_CHARACTER_HEX_FINGERPRINT="86A32BE7AB448F546095841B16F66731F8F57B73" # If unset or empty, generate unsigned AppImage (⚠️ WARNING! NOT RECOMMENDED IN PRODUCTION!)
