SIGN_KEYSTORE="$HOME/keystore.p12" # Use unexisting keystore file to generate default keystore (⚠️ WARNING! NOT RECOMMENDED IN PRODUCTION!)
SIGN_STORETYPE="PKCS12"
SIGN_ALIAS="signing_alias"
SIGN_KEYPASS="your_password"
SIGN_STOREPASS="your_password"
